# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_nad_frontenduser_get_collection:
    pattern:   /frontenduser/
    defaults:  { _controller: NADFrontendUserBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_nad_frontenduser_get:
    pattern:   /frontenduser/{id}
    defaults:  { _controller: NADFrontendUserBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

admin_api_nad_frontenduser_put:
    pattern:   /frontenduser/{id}
    defaults:  { _controller: NADFrontendUserBundle:Admin/Api:put, _format: json }
    requirements:
        _method: PUT

admin_api_nad_frontenduser_delete:
    pattern:   /frontenduser/{id}
    defaults:  { _controller: NADFrontendUserBundle:Admin/Api:delete, _format: json }
    requirements:
        _method: DELETE

admin_api_nad_frontenduser_post:
    pattern:   /frontenduser/
    defaults:  { _controller: NADFrontendUserBundle:Admin/Api:post, _format: json }
    requirements:
        _method: POST
