<?php

namespace NAD\ProductBundle\Entity;

use NAD\ResourceBundle\Entity\AbstractCollectionRepository;

/**
 * CategoryRepository for Products
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends AbstractCollectionRepository
{
    protected $model = 'NADProductBundle:Category';
}
