# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    nad_navigation_manager.class: NAD\NavigationBundle\Manager\NavigationManager
    nad_navigation_node_manager.class: NAD\NavigationBundle\Manager\NodeManager

services:
    nad.navigation.node.manager:
        class: %nad_navigation_node_manager.class%
        arguments:
          - @doctrine.orm.entity_manager
          - "%locales%"
