# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_nad_addressing_city_get_collection:
    pattern:  /addressing/city/
    defaults: { _controller: NADAddressingBundle:Admin/ApiCity:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_nad_addressing_city_get:
    pattern:  /addressing/city/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiCity:get, _format: json }
    requirements:
        _method: GET

admin_api_nad_addressing_city_post:
    pattern:  /addressing/city/
    defaults: { _controller: NADAddressingBundle:Admin/ApiCity:post, _format: json }
    requirements:
        _method: POST

admin_api_nad_addressing_city_put:
    pattern:  /addressing/city/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiCity:put, _format: json }
    requirements:
        _method: PUT

admin_api_nad_addressing_city_delete:
    pattern:  /addressing/city/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiCity:delete, _format: json }
    requirements:
        _method: DELETE

#Region
admin_api_nad_addressing_region_get_collection:
    pattern:  /addressing/region/
    defaults: { _controller: NADAddressingBundle:Admin/ApiRegion:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_nad_addressing_region_get:
    pattern:  /addressing/region/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiRegion:get, _format: json }
    requirements:
        _method: GET

admin_api_nad_addressing_region_post:
    pattern:  /addressing/region/
    defaults: { _controller: NADAddressingBundle:Admin/ApiRegion:post, _format: json }
    requirements:
        _method: POST

admin_api_nad_addressing_region_put:
    pattern:  /addressing/region/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiRegion:put, _format: json }
    requirements:
        _method: PUT

admin_api_nad_addressing_region_delete:
    pattern:  /addressing/region/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiRegion:delete, _format: json }
    requirements:
        _method: DELETE


#Countries
admin_api_nad_addressing_country_get_collection:
    pattern:  /addressing/country/
    defaults: { _controller: NADAddressingBundle:Admin/ApiCountry:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_nad_addressing_country_get:
    pattern:  /addressing/country/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiCountry:get, _format: json }
    requirements:
        _method: GET

admin_api_nad_addressing_country_post:
    pattern:  /addressing/country/
    defaults: { _controller: NADAddressingBundle:Admin/ApiCountry:post, _format: json }
    requirements:
        _method: POST

admin_api_nad_addressing_country_put:
    pattern:  /addressing/country/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiCountry:put, _format: json }
    requirements:
        _method: PUT

admin_api_nad_addressing_country_delete:
    pattern:  /addressing/country/{id}
    defaults: { _controller: NADAddressingBundle:Admin/ApiCountry:delete, _format: json }
    requirements:
        _method: DELETE
