# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

be_api_nad_product:
    resource: "@NADAddressingBundle/Resources/config/routing/administrator.yml"
    prefix:   /%backend_api%

fe_api_nad_product:
    resource: "@NADAddressingBundle/Resources/config/routing/site.yml"
    prefix:   /%frontend_api%
