imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: twig.yml }

    - { resource: configs/nad.yml }
    - { resource: configs/payum.yml }
    - { resource: configs/cors.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 0
        save_path: %kernel.root_dir%/var/sessions
        name: AISELSESSID
#        cookie_domain: .nad.dev
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
    filters:
        cssrewrite: ~

# Annotations
sensio_framework_extra:
    view:
        annotations: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    NADPageBundle:
                        type: annotation
                    NADAddressingBundle:
                        type: annotation
                    NADFrontendUserBundle:
                        type: annotation
                    NADBackendUserBundle:
                        type: annotation
                    NADConfigBundle:
                        type: annotation
                    NADCartBundle:
                        type: annotation
                    NADProductBundle:
                        type: annotation
                    NADNavigationBundle:
                        type: annotation
                    NADOrderBundle:
                        type: annotation

                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    payum:
                        is_bundle: false
                        type: xml
                        dir: %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping
                        prefix: Payum\Core\Model

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    spool:     { type: memory }

# Fields serialization
jms_serializer:
  metadata:
    auto_detection: true

# REST
fos_rest:
    view:
        view_response_listener: 'force'
