<?php

namespace NAD\AddressingBundle\Entity;

use NAD\ResourceBundle\Entity\AbstractCollectionRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends AbstractCollectionRepository
{
    protected $model = 'NADAddressingBundle:Region';

}
