<?php

namespace NAD\AddressingBundle\Entity;

use NAD\ResourceBundle\Entity\AbstractCollectionRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends AbstractCollectionRepository
{
    protected $model = 'NADAddressingBundle:City';

}
