<?php

namespace NAD\AddressingBundle\Entity;

use NAD\ResourceBundle\Entity\AbstractCollectionRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends AbstractCollectionRepository
{
    protected $model = 'NADAddressingBundle:Country';

}
