<?php

namespace NAD\AddressingBundle\Entity;

use NAD\ResourceBundle\Entity\AbstractCollectionRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends AbstractCollectionRepository
{
    protected $model = 'NADAddressingBundle:Region';

}
