# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    nad_order_manager.class: NAD\OrderBundle\Manager\OrderManager
    nad_invoice_manager.class: NAD\OrderBundle\Manager\InvoiceManager

services:
    nad.order.manager:
        class: %nad_order_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @nad.config.manager
            - @nad.cart.manager

    nad.invoice.manager:
        class: %nad_invoice_manager.class%
        arguments:
          - @doctrine.orm.entity_manager
