# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_nad_navigation_get:
    pattern:   /navigation/{id}
    defaults:  { _controller: NADNavigationBundle:Admin/ApiNode:get, _format: json }
    requirements:
        _method: GET

admin_api_nad_navigation_get_tree:
    pattern:   /navigation/
    defaults:  { _controller: NADNavigationBundle:Admin/ApiNodeEdit:getNodeCollection, _format: json }
    requirements:
        _method: GET

admin_api_nad_navigation_put:
    pattern:   /navigation/{id}
    defaults:  { _controller: NADNavigationBundle:Admin/ApiNode:put, _format: json }
    requirements:
        _method: PUT

admin_api_nad_navigation_post:
    pattern:   /navigation/
    defaults:  { _controller: NADNavigationBundle:Admin/ApiNode:post, _format: json }
    requirements:
        _method: POST

admin_api_nad_navigation_delete:
    pattern:   /navigation/{id}
    defaults:  { _controller: NADNavigationBundle:Admin/ApiNode:delete, _format: json }
    requirements:
        _method: DELETE

admin_api_nad_navigation_node_edit:
    pattern:   /navigation/node/
    defaults:  { _controller: NADNavigationBundle:Admin/ApiNodeEdit:nodeEdit, _format: json }
    requirements:
        _method: GET
