# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_nad_navigationmenu:
    pattern:  /{locale}/navigation/
    defaults: { _controller: NADNavigationBundle:Api:getNodeCollectionEnabled, _format: json }
    requirements:
        _method: GET
