# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Backend
admin_api_nad_config_get:
    pattern:   /%backend_api%/config/
    defaults:  { _controller: NADConfigBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

admin_api_nad_config_put:
    pattern:   /%backend_api%/config/
    defaults:  { _controller: NADConfigBundle:Admin/Api:save, _format: json }
    requirements:
        _method: PUT

# Frontend
api_nad_config:
    pattern:  /%frontend_api%/{locale}/config/
    defaults:  { _controller: NADConfigBundle:Api:get, _format: json }
    requirements:
        _method: GET
