# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    administrator.user.manager:
        class: NAD\BackendUserBundle\Manager\UserManager
        arguments:
          - @doctrine.orm.entity_manager
          - @security.encoder_factory
          - @security.context
