# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Frontend
api_nad_product_get_collection:
    pattern:  /{locale}/product/
    defaults: { _controller: NADProductBundle:ApiProduct:getCollection, _format: json }
    requirements:
        _method: GET

api_nad_product_get_by_url:
    pattern:  /{locale}/product/{urlKey}
    defaults: { _controller: NADProductBundle:ApiProduct:productViewByURL, _format: json }
    requirements:
        _method: GET

api_nad_product_categoryview:
    pattern:  /{locale}/product/category/{urlKey}
    defaults: { _controller: NADProductBundle:ApiNode:categoryView, _format: json }
    requirements:
        _method: GET
        id: "\d+"

api_nad_product_category_get:
    pattern:  /{locale}/product/category/
    defaults: { _controller: NADProductBundle:ApiNode:categoryList, _format: json }
    requirements:
        _method: GET

api_nad_product_category_get_tree:
    pattern:  /{locale}/product/category/tree/
    defaults: { _controller: NADProductBundle:ApiNode:getNodeCollectionEnabled, _format: json }
    requirements:
        _method: GET
