# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_nad_cart_details:
    pattern:  /%frontend_api%/cart/
    defaults: { _controller: NADCartBundle:ApiCart:cart, _format: json }
    requirements:
        _method: GET

api_nad_cart_add:
    pattern:  /%frontend_api%/cart/product/{productId}/qty/{qty}/add.json
    defaults: { _controller: NADCartBundle:ApiCart:cartProductAdd, _format: json }
    requirements:
        _method: POST

api_nad_cart_update:
    pattern:  /%frontend_api%/cart/product/{productId}/qty/{qty}/update.json
    defaults: { _controller: NADCartBundle:ApiCart:cartProductUpdate, _format: json }
    requirements:
        _method: GET
