# This file is part of the NAD package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    nad_search_manager.class: NAD\SearchBundle\Manager\SearchManager

services:
    nad.search.manager:
        class: %nad_search_manager.class%
        arguments: [@doctrine.orm.entity_manager]
